# -*- coding: utf-8 -*-
"""Algoritmo-de-Auditoria-de-Dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLK3j_QA80L0X4_JqgfJ38Sc3l_vLrBD
"""

# Configuração Global

# Define o limite inicial de segurança (pode ser alterado depois)

LIMITE_SEGURANCA = 10000.00



def analisar_vendas(v1, v2, v3):

  # A palavra-chave 'global' permite que a gente modifique a variável

  # LIMITE_SEGURANCA que foi criada fora desta função.

  global LIMITE_SEGURANCA



  # Verifica se alguma das vendas ultrapassou o limite atual

  maior_venda = max(v1, v2, v3)

  if maior_venda > LIMITE_SEGURANCA:

    print(f"\nAtenção: Uma venda de R$ {maior_venda:.2f} ultrapassou o limite de R$ {LIMITE_SEGURANCA:.2f}.")

    resposta = input("Gerente, deseja alterar o Limite de Segurança? (s/n): ")



    if resposta.lower() == 's':

      # Fazendo casting novamente para garantir que o novo limite seja decimal

      novo_limite = float(input("novo valor do limite: R$ "))

      LIMITE_SEGURANCA = novo_limite

      print(f"Limite atualizado com sucesso para: R$ {LIMITE_SEGURANCA:.2f}\n")



  # Calculando a Média Simples

  media = (v1 + v2 + v3) / 3

  print(f"\n--- Resultados da Auditoria ---")

  print(f"Média de vendas do dia: R$ {media:.2f}")



  # Lógica de Investigação 1: Média maior que o limite

  if media > LIMITE_SEGURANCA:

    print("SISTEMA EM QUARENTENA")



  # Lógica de Investigação 2: Discrepância (venda 5x maior que a média)

  if v1 > (2 * media) or v2 > (2 * media) or v3 > (2 * media):

    print("REVISÃO MANUAL")



  # Apresentação: Mostrando os tipos de dados usando f-strings

  print("\n--- Verificação de Tipos de Dados (Casting) ---")

  print(f"Venda 1: {type(v1)}")

  print(f"Venda 2: {type(v2)}")

  print(f"Venda 3: {type(v3)}")

  print(f"Limite de Segurança: {type(LIMITE_SEGURANCA)}")





# --- Início do Programa Principal ---

print("Bem-vindo ao Sistema de Auditoria de Vendas Semanais")



# Entrada de Dados e Casting

# O 'input' pega o texto, e o 'float()' transforma em número com vírgula

venda_1 = float(input("valor da 1ª venda: R$ "))

venda_2 = float(input("valor da 2ª venda: R$ "))

venda_3 = float(input("valor da 3ª venda: R$ "))



# Chama a função passando as três vendas digitadas

analisar_vendas(venda_1, venda_2, venda_3)